#cloud-config
package_update: true
package_upgrade: true

apt:
  primary:
    - arches: [default]
      uri: https://mirrors.tuna.tsinghua.edu.cn/ubuntu/

packages:
  - net-tools
  - dnsutils
  - docker.io
  - docker-compose
  - neovim
  - tmux
  - neofetch
  - fzf
