#cloud-config
system_info:
  default_user:
    name: shikun

apt:
  primary:
    - arches: [default]
      uri: https://mirrors.tuna.tsinghua.edu.cn/ubuntu/

package_update: true
package_upgrade: true

packages:
  - net-tools
  - dnsutils
  - docker.io
  - docker-compose
  - neovim
  - tmux
  - neofetch
  - fzf
